### ISSUE TITLE
打不开真题啊

### ISSUE THREAD

**Issue by close2ming** [Mingasd/Jiangsu-university-885#1]
pdf格式的真题下载不了 也看不了

**Comment by Mingasd** [comment]
> pdf格式的真题下载不了 也看不了
我刚试过是可以下载的，可能是因为你的网络问题，你可以去gitee上搜一下，我看有人把我这个仓库搬过去了

**Comment by jus2Bclose2u** [comment]
应该是我的问题  但是学长有没有近期江大的初试题啊       方便加个qq吗  我的QQ：411066544
